Repository inferablehq/inferable, pull requests merged in 2024-12, with the labels that each got.

#394 fix: Refactor useRun hook and introduce useRuns.
  .github/workflows/build.yml
  sdk-react/README.md
  sdk-react/jest.config.js
  sdk-react/jest.setup.js
  sdk-react/package-lock.json
  sdk-react/package.json
  sdk-react/src/contract.ts
  sdk-react/src/createClient.ts
  sdk-react/src/hooks/__tests__/useRun.test.tsx
  sdk-react/src/hooks/useRun.test.ts
  sdk-react/src/hooks/useRun.ts
  sdk-react/src/hooks/util.ts
Labels: Review effort [1-5]: 4

#396 fix: Allow message history with only template message
  control-plane/src/modules/workflows/agent/overflow.ts
Labels: Review effort [1-5]: 1

#397 chore: Update package version to 0.0.11
  sdk-react/package-lock.json
  sdk-react/package.json
Labels: Review effort [1-5]: 1

#399 chore: Remove missing result log
  control-plane/src/modules/calls/router.ts
Labels: Review effort [1-5]: 1

#400 feat: Integrate background run ID for cluster operations
  control-plane/src/modules/auth/custom.ts
  control-plane/src/modules/calls/router.ts
  control-plane/src/modules/data.ts
  control-plane/src/modules/jobs/create-job.ts
  control-plane/src/modules/jobs/jobs.test.ts
  control-plane/src/modules/jobs/persist-result.test.ts
  control-plane/src/modules/jobs/persist-result.ts
  control-plane/src/modules/observability/events.test.ts
  control-plane/src/modules/tool-metadata.ts
  control-plane/src/modules/workflows/notify.ts
  control-plane/src/modules/workflows/workflows.ts
Labels: Review effort [1-5]: 2

#402 chore: Add prepublish script to sdk-react/package.json
  sdk-react/package-lock.json
  sdk-react/package.json
Labels: Review effort [1-5]: 1

#404 fix: Remove redundant validation for initialPrompt or configId
  .github/workflows/build.yml
  control-plane/src/modules/workflows/router.ts
Labels: Review effort [1-5]: 1

#403 chore: Add .npmignore and bump version to 0.0.13
  sdk-react/.npmignore
  sdk-react/package-lock.json
  sdk-react/package.json
Labels: Review effort [1-5]: 1

#405 chore: Remove redundant final-step from build workflow
  .github/workflows/build.yml
Labels: Review effort [1-5]: 1

#406 chore: Remove unused health and constants modules
  control-plane/package.json
  control-plane/src/modules/health.ts
  control-plane/src/utilities/constants.ts
Labels: Review effort [1-5]: 1

#401 feat: Slack / Nango integration
  app/app/clusters/[clusterId]/integrations/page.tsx
  app/app/clusters/[clusterId]/integrations/slack/page.tsx
  app/client/contract.ts
  app/package-lock.json
  app/package.json
  control-plane/drizzle/0198_daily_smasher.sql
  control-plane/drizzle/meta/0198_snapshot.json
  control-plane/drizzle/meta/_journal.json
  control-plane/package-lock.json
  control-plane/package.json
  control-plane/src/index.ts
  control-plane/src/modules/contract.ts
  control-plane/src/modules/data.ts
  control-plane/src/modules/integrations/constants.ts
  control-plane/src/modules/integrations/integrations.ts
  control-plane/src/modules/integrations/nango/index.ts
  control-plane/src/modules/integrations/router.ts
  control-plane/src/modules/integrations/schema.ts
  control-plane/src/modules/integrations/slack/index.ts
  control-plane/src/modules/integrations/slack/receiver.ts
  control-plane/src/modules/integrations/tavily.ts
  control-plane/src/modules/integrations/toolhouse.ts
  control-plane/src/modules/integrations/types.ts
  control-plane/src/modules/integrations/valtown.ts
  control-plane/src/modules/jobs/external.ts
  control-plane/src/modules/slack/index.test.ts
  control-plane/src/modules/workflows/notify.ts
  control-plane/src/utilities/env.ts
Labels: Review effort [1-5]: 4

#408 feat: Allow useRun to specify a resultSchema
  sdk-react/demo/TestPage.tsx
  sdk-react/package-lock.json
  sdk-react/package.json
  sdk-react/src/hooks/useRun.ts
Labels: Review effort [1-5]: 2

#409 feat: Cleanup conflicting Slack integrations
  control-plane/src/modules/integrations/slack/index.ts
  control-plane/src/modules/integrations/types.ts
Labels: Review effort [1-5]: 2

#410 chore: Add some additional logging to slack integration
  control-plane/src/modules/integrations/slack/index.ts
Labels: Review effort [1-5]: 2

#411 fix: Correctly cleanup existing slack integrations
  control-plane/src/modules/integrations/integrations.ts
  control-plane/src/modules/integrations/slack/index.ts
  control-plane/src/modules/integrations/types.ts
Labels: Review effort [1-5]: 2

#412 feat: Authenticate Slack message users
  control-plane/.env.base
  control-plane/package-lock.json
  control-plane/package.json
  control-plane/src/modules/auth/auth.test.ts
  control-plane/src/modules/clerk.ts
  control-plane/src/modules/integrations/slack/index.ts
  control-plane/src/modules/router.ts
  control-plane/src/modules/workflows/router.ts
  control-plane/src/modules/workflows/workflow-messages.ts
  control-plane/src/modules/workflows/workflows.ts
  control-plane/src/utilities/env.ts
Labels: Review effort [1-5]: 3

#413 fix: Handle Clerk auth gracefully
  control-plane/src/modules/integrations/slack/index.ts
Labels: Review effort [1-5]: 1

#414 fix: Correct Slack auth error formatting
  control-plane/src/modules/integrations/slack/index.ts
Labels: Review effort [1-5]: 1

#416 fix: Correct external service name casing
  control-plane/src/modules/integrations/tavily.ts
  control-plane/src/modules/integrations/toolhouse.ts
  control-plane/src/modules/integrations/valtown.ts
Labels: Review effort [1-5]: 1

#417 fix: Minor changes to @inferable/react for memoization and error handling
  sdk-react/README.md
  sdk-react/demo/TestPage.tsx
  sdk-react/package-lock.json
  sdk-react/package.json
  sdk-react/src/hooks/useRun.ts
Labels: Review effort [1-5]: 2

#422 feat: Slack approvals
  control-plane/src/modules/calls/router.ts
  control-plane/src/modules/integrations/slack/index.ts
  control-plane/src/modules/jobs/jobs.test.ts
  control-plane/src/modules/jobs/jobs.ts
  control-plane/src/modules/workflows/notify.ts
Labels: Review effort [1-5]: 3

#423 chore: Delete ui-embeddable adapter files
  adapters/ui-embeddable/.gitignore
  adapters/ui-embeddable/README.md
  adapters/ui-embeddable/app/favicon.ico
  adapters/ui-embeddable/app/globals.css
  adapters/ui-embeddable/app/layout.tsx
  adapters/ui-embeddable/app/page.tsx
  adapters/ui-embeddable/eslint.config.mjs
  adapters/ui-embeddable/next.config.ts
  adapters/ui-embeddable/package-lock.json
  adapters/ui-embeddable/package.json
  adapters/ui-embeddable/postcss.config.mjs
  adapters/ui-embeddable/public/file.svg
  adapters/ui-embeddable/public/globe.svg
  adapters/ui-embeddable/public/next.svg
  adapters/ui-embeddable/public/vercel.svg
  adapters/ui-embeddable/public/window.svg
  adapters/ui-embeddable/tailwind.config.ts
  adapters/ui-embeddable/tsconfig.json
Labels: Review effort [1-5]: 1

#424 fix: Implement HTTP signing for Val.town API requests
  control-plane/src/modules/integrations/valtown.test.ts
  control-plane/src/modules/integrations/valtown.ts
  control-plane/src/utilities/env.ts
Labels: Review effort [1-5]: 2

#425 chore: Move Slack approval text to top level
  control-plane/src/modules/integrations/slack/index.ts
Labels: Review effort [1-5]: 1

#426 fix: Include block and fallback text for approval
  control-plane/src/modules/integrations/slack/index.ts
Labels: Review effort [1-5]: 2

#427 chore: Export interrupt.approval()
  sdk-node/src/index.ts
  sdk-node/src/util.ts
Labels: Review effort [1-5]: 1

#434 feat: Implement asymmetric encryption for signing Val.town requests
  app/app/clusters/[clusterId]/integrations/valtown/page.tsx
  app/client/contract.ts
  control-plane/package-lock.json
  control-plane/package.json
  control-plane/src/modules/contract.ts
  control-plane/src/modules/data.ts
  control-plane/src/modules/integrations/schema.ts
  control-plane/src/modules/integrations/valtown.test.ts
  control-plane/src/modules/integrations/valtown.ts
  control-plane/src/utilities/env.ts
Labels: Review effort [1-5]: 4

#433 fix: Set default workflow_id and enforce non-null constraint
  control-plane/drizzle/0199_curious_mach_iv.sql
  control-plane/drizzle/meta/0199_snapshot.json
  control-plane/drizzle/meta/_journal.json
Labels: Review effort [1-5]: 1

#437 fix: Add deletion step before upserting service definition in ValTown integration
  control-plane/src/modules/integrations/valtown.ts
Labels: Review effort [1-5]: 1

#435 fix: Remove unused endpoint' field from valtownMetaSchema
  control-plane/src/modules/integrations/valtown.test.ts
  control-plane/src/modules/integrations/valtown.ts
Labels: Review effort [1-5]: 1

#438 fix: Correct private key formatting for consistent handling
  control-plane/src/modules/integrations/valtown.ts
Labels: Review effort [1-5]: 2

#439 feat: Initial email ingestion
  .github/workflows/build.yml
  control-plane/docker-compose.dev.yml
  control-plane/scripts/sendTestEmail.sh
  control-plane/src/index.ts
  control-plane/src/modules/email/index.ts
  control-plane/src/utilities/env.ts
Labels: Review effort [1-5]: 2

#440 fix: Convert request signing to use JWK format
  adapters/valtown-adapter/jsr.json
  adapters/valtown-adapter/mod.ts
  app/app/clusters/[clusterId]/integrations/valtown/page.tsx
  control-plane/package.json
  control-plane/src/modules/integrations/valtown.test.ts
  control-plane/src/modules/integrations/valtown.ts
Labels: Review effort [1-5]: 4

#442 fix: Replace key pair with token for Val.town integration
  app/app/clusters/[clusterId]/integrations/valtown/page.tsx
  app/client/contract.ts
  control-plane/src/modules/contract.ts
  control-plane/src/modules/data.ts
  control-plane/src/modules/integrations/schema.ts
  control-plane/src/modules/integrations/valtown.test.ts
  control-plane/src/modules/integrations/valtown.ts
Labels: Review effort [1-5]: 3

#444 chore: Remove redundant ServicesQuickstart component from page.tsx
  app/app/clusters/[clusterId]/runs/page.tsx
Labels: Review effort [1-5]: 1

#445 feat: Adding the val.town adapter
  adapters/valtown-adapter/README.md
  adapters/valtown-adapter/jsr.json
  adapters/valtown-adapter/mod.ts
  adapters/valtown-adapter/valtown.mov.gif
Labels: Review effort [1-5]: 2
