Repository inferablehq/inferable, pull requests merged in 2025-01, with the labels that each got.

#446 feat: Email run triggering
  control-plane/package-lock.json
  control-plane/package.json
  control-plane/scripts/sendTestEmail.sh
  control-plane/scripts/sendTestEmail.ts
  control-plane/src/modules/clerk.ts
  control-plane/src/modules/email/index.test.ts
  control-plane/src/modules/email/index.ts
  control-plane/src/modules/email/test.util.ts
  control-plane/src/modules/integrations/slack/index.ts
  control-plane/src/modules/jobs/external.ts
  control-plane/src/modules/sqs.ts
  control-plane/src/modules/workflows/queues.ts
  control-plane/src/modules/workflows/workflows.ts
  control-plane/src/utilities/env.ts
Labels: Review effort [1-5]: 4

#447 fix: Implement long polling for timeline updates and refactor message handling
  app/app/clusters/page.tsx
  app/app/layout.tsx
  app/client/contract.ts
  app/components/chat/InvocationResult.tsx
  app/components/chat/ai-message.tsx
  app/components/clusters-table.tsx
  app/components/ui/data-table.tsx
  app/components/workflow.tsx
  control-plane/src/index.ts
  control-plane/src/modules/contract.ts
  control-plane/src/modules/jobs/jobs.ts
  control-plane/src/modules/observability/events.ts
  control-plane/src/modules/router.ts
  control-plane/src/modules/timeline.ts
  control-plane/src/modules/util.ts
  control-plane/src/modules/workflows/agent/tools/functions.ts
  control-plane/src/modules/workflows/router.ts
  control-plane/src/modules/workflows/workflow-messages.ts
  control-plane/src/modules/workflows/workflows.ts
Labels: Review effort [1-5]: 4

#448 feat: Send run replies via email thread
  control-plane/package-lock.json
  control-plane/package.json
  control-plane/scripts/sendTestEmail.ts
  control-plane/src/modules/email/index.test.ts
  control-plane/src/modules/email/index.ts
  control-plane/src/modules/email/test.util.ts
  control-plane/src/modules/integrations/slack/index.ts
  control-plane/src/modules/ses.ts
  control-plane/src/modules/workflows/notify.ts
Labels: Review effort [1-5]: 3

#450 chore: Refactor layout to use ClusterRunsLayout component
  app/app/clusters/[clusterId]/runs/layout.tsx
  app/app/clusters/[clusterId]/runs/page.tsx
  app/components/cluster-runs-layout.tsx
Labels: Review effort [1-5]: 3

#451 feat: Reply to Email initiated runs
  control-plane/scripts/sendTestEmail.ts
  control-plane/src/modules/data.ts
  control-plane/src/modules/email/index.ts
  control-plane/src/modules/email/test.util.ts
  control-plane/src/modules/integrations/slack/index.ts
  control-plane/src/modules/workflows/agent/run.ts
  control-plane/src/modules/workflows/notify.ts
  control-plane/src/modules/workflows/workflow-messages.ts
Labels: Review effort [1-5]: 3

#452 chore: Additional SNS failure logging
  control-plane/src/modules/email/index.ts
Labels: Review effort [1-5]: 1

#449 fix: Correct cache TTL units from ms to s
  control-plane/src/bootstrap.ts
  control-plane/src/index.ts
  control-plane/src/modules/auth/auth.ts
  control-plane/src/modules/cluster.ts
  control-plane/src/modules/cron.ts
  control-plane/src/modules/server-stats.ts
  control-plane/src/modules/workflows/agent/tools/cluster-internal-tools.ts
  control-plane/src/utilities/cache.ts
Labels: Review effort [1-5]: 3

#454 feat: Strip email chain quotes
  control-plane/src/modules/email/index.test.ts
  control-plane/src/modules/email/index.ts
Labels: Review effort [1-5]: 2

#455 chore: Include name in email address
  control-plane/src/modules/email/index.ts
Labels: Review effort [1-5]: 1

#459 chore: Consolidate message schemas into unified structure
  app/client/contract.ts
  app/components/chat/InvocationResult.tsx
  app/components/chat/ai-message.tsx
  app/components/chat/human-message.tsx
  app/components/chat/markdown.tsx
  app/components/chat/template-mesage.tsx
  app/components/chat/workflow-event.tsx
  app/components/workflow.tsx
  control-plane/src/modules/contract.ts
  control-plane/src/modules/data.ts
  control-plane/src/modules/email/index.ts
  control-plane/src/modules/integrations/slack/index.ts
  control-plane/src/modules/router.ts
  control-plane/src/modules/workflows/agent/agent.ai.test.ts
  control-plane/src/modules/workflows/agent/nodes/edges.test.ts
  control-plane/src/modules/workflows/agent/nodes/model-call.test.ts
  control-plane/src/modules/workflows/agent/nodes/model-call.ts
  control-plane/src/modules/workflows/agent/nodes/tool-call.test.ts
  control-plane/src/modules/workflows/agent/nodes/tool-call.ts
  control-plane/src/modules/workflows/agent/run.ts
  control-plane/src/modules/workflows/agent/state.ts
  control-plane/src/modules/workflows/router.ts
  control-plane/src/modules/workflows/workflow-messages.ts
  control-plane/src/modules/workflows/workflows.ts
  control-plane/src/utilities/cache.ts
Labels: Review effort [1-5]: 4

#460 feat: New react hooks: useInferable, useRun, and useMessages
  app/components/chat/template-message.tsx
  control-plane/src/modules/contract.ts
  control-plane/src/modules/router.ts
  control-plane/src/modules/workflows/workflow-messages.ts
  sdk-react/README.md
  sdk-react/demo/TestPage.css
  sdk-react/demo/TestPage.tsx
  sdk-react/demo/main.jsx
  sdk-react/package-lock.json
  sdk-react/package.json
  sdk-react/src/contract.ts
  sdk-react/src/hooks/useInferable.test.ts
  sdk-react/src/hooks/useInferable.ts
  sdk-react/src/hooks/useInterval.ts
  sdk-react/src/hooks/useMessages.test.ts
  sdk-react/src/hooks/useMessages.ts
  sdk-react/src/hooks/useRun.test.ts
  sdk-react/src/hooks/useRun.ts
  sdk-react/src/index.ts
Labels: Review effort [1-5]: 4

#461 feat: Make listMessages polling configurable
  control-plane/src/modules/contract.ts
  control-plane/src/modules/router.ts
  control-plane/src/modules/workflows/workflow-messages.ts
  control-plane/src/modules/workflows/workflows.ts
  sdk-react/src/contract.ts
  sdk-react/src/hooks/useRun.ts
Labels: Review effort [1-5]: 2

#463 fix: Add missing metadata to test messages in agent.ai.test.ts
  control-plane/src/modules/workflows/agent/agent.ai.test.ts
Labels: Review effort [1-5]: 1

#457 feat: Enforce custom auth userId value
  app/app/clusters/[clusterId]/settings/details/page.tsx
  app/components/WorkflowList.tsx
  control-plane/drizzle/0200_organic_terror.sql
  control-plane/drizzle/meta/0200_snapshot.json
  control-plane/drizzle/meta/_journal.json
  control-plane/src/modules/auth/auth.test.ts
  control-plane/src/modules/auth/auth.ts
  control-plane/src/modules/auth/cluster.ts
  control-plane/src/modules/auth/custom.ts
  control-plane/src/modules/data.ts
  control-plane/src/modules/workflows/metadata.ts
  control-plane/src/modules/workflows/router.ts
  control-plane/src/modules/workflows/workflows.ts
Labels: Review effort [1-5]: 2

#465 fix: Correct SQL query for displayable context extraction
  control-plane/src/modules/workflows/workflow-messages.ts
Labels: Review effort [1-5]: 2

#466 feat: Rename runConfig -> agent usage in API
  app/app/clusters/[clusterId]/configs/[promptId]/edit/page.tsx
  app/app/clusters/[clusterId]/configs/new/page.tsx
  app/app/clusters/[clusterId]/configs/page.tsx
  app/app/clusters/[clusterId]/settings/details/page.tsx
  app/client/contract.ts
  app/components/PromptMetricsCharts.tsx
  app/components/WorkflowList.tsx
  app/components/breadcrumbs.tsx
  app/components/chat/ai-message.tsx
  app/components/chat/prompt-textarea.tsx
  app/components/chat/template-search.tsx
  app/components/workflow-tab.tsx
  control-plane/drizzle/0201_clumsy_human_torch.sql
  control-plane/drizzle/0202_daffy_baron_zemo.sql
  control-plane/drizzle/meta/0201_snapshot.json
  control-plane/drizzle/meta/0202_snapshot.json
  control-plane/drizzle/meta/_journal.json
  control-plane/src/modules/agents.test.ts
  control-plane/src/modules/agents.ts
  control-plane/src/modules/auth/auth.test.ts
  control-plane/src/modules/auth/auth.ts
  control-plane/src/modules/cluster-export.ts
  control-plane/src/modules/contract.ts
  control-plane/src/modules/data.ts
  control-plane/src/modules/embeddings/embeddings.ts
  control-plane/src/modules/management.ts
  control-plane/src/modules/router.ts
  control-plane/src/modules/workflows/metadata.ts
  control-plane/src/modules/workflows/router.ts
  control-plane/src/modules/workflows/workflows.ts
Labels: Review effort [1-5]: 4

#467 feat: Rename runConfig -> agent in Playground
  app/app/clusters/[clusterId]/agents/[agentId]/edit/page.tsx
  app/app/clusters/[clusterId]/agents/global/page.tsx
  app/app/clusters/[clusterId]/agents/layout.tsx
  app/app/clusters/[clusterId]/agents/new/page.tsx
  app/app/clusters/[clusterId]/agents/page.tsx
  app/components/AgentMetrticsCharts.tsx
  app/components/breadcrumbs.tsx
  app/components/chat/agent-form.tsx
  app/components/chat/prompt-textarea.tsx
  app/components/workflow-tab.tsx
Labels: Review effort [1-5]: 4

#468 chore: Bump node SDK ts-rest contract
  sdk-node/src/contract.ts
Labels: Review effort [1-5]: 4

#469 fix: Correct syntax errors in job recovery mechanism
  cli/src/client/contract.ts
  control-plane/drizzle/0203_sad_speed.sql
  control-plane/drizzle/meta/0203_snapshot.json
  control-plane/drizzle/meta/_journal.json
  control-plane/src/modules/auth/custom.test.ts
  control-plane/src/modules/data.ts
  control-plane/src/modules/jobs/create-job.ts
  control-plane/src/modules/jobs/job-results.ts
  control-plane/src/modules/jobs/jobs.test.ts
  control-plane/src/modules/jobs/jobs.ts
  control-plane/src/modules/jobs/persist-result.test.ts
  control-plane/src/modules/jobs/persist-result.ts
  control-plane/src/modules/jobs/self-heal-jobs.ts
  control-plane/src/modules/machines.test.ts
  control-plane/src/modules/machines.ts
  control-plane/src/modules/management.ts
Labels: Review effort [1-5]: 3

#472 chore: Apply un-applied migrations
  control-plane/drizzle/0204_melodic_ikaris.sql
  control-plane/drizzle/meta/0204_snapshot.json
  control-plane/drizzle/meta/_journal.json
Labels: Review effort [1-5]: 1

#473 feat: Rename workflow_metadata -> run_tags
  app/client/contract.ts
  app/components/workflow.tsx
  control-plane/src/modules/contract.ts
  control-plane/src/modules/data.ts
  control-plane/src/modules/email/index.ts
  control-plane/src/modules/integrations/slack/index.ts
  control-plane/src/modules/workflows/agent/run.ts
  control-plane/src/modules/workflows/notify.ts
  control-plane/src/modules/workflows/queues.ts
  control-plane/src/modules/workflows/router.ts
  control-plane/src/modules/workflows/tags.test.ts
  control-plane/src/modules/workflows/tags.ts
  control-plane/src/modules/workflows/workflows.ts
  sdk-node/src/contract.ts
  sdk-node/src/types.ts
Labels: Review effort [1-5]: 3

#475 chore: Cleanup `configId` and `metadata` in Run API
  app/client/contract.ts
  control-plane/src/modules/contract.ts
  control-plane/src/modules/workflows/notify.ts
  control-plane/src/modules/workflows/router.ts
  sdk-node/package.json
  sdk-node/src/contract.ts
Labels: Review effort [1-5]: 2

#478 fix: Template message parsing
  app/app/clusters/[clusterId]/agents/[agentId]/edit/page.tsx
  app/client/contract.ts
  app/components/WorkflowList.tsx
  app/components/chat/template-mesage.tsx
  app/components/chat/template-message.tsx
  app/components/workflow-tab.tsx
  app/components/workflow.tsx
  control-plane/src/modules/contract.ts
  control-plane/src/modules/workflows/workflow-messages.ts
Labels: Review effort [1-5]: 3

#479 fix: Correct usage of unifiedMessageSchema
  control-plane/src/modules/contract.ts
  control-plane/src/modules/email/index.ts
  control-plane/src/modules/integrations/slack/index.ts
  control-plane/src/modules/workflows/workflow-messages.ts
Labels: Review effort [1-5]: 2

#477 chore: Rename metadata->tags in OnStatusChangeInput
  sdk-dotnet/src/Inferable.cs
Labels: Review effort [1-5]: 1

#481 fix: Corerct Clerk ID formatting in slack / email modules
  control-plane/src/modules/email/index.ts
  control-plane/src/modules/integrations/slack/index.ts
Labels: Review effort [1-5]: 2

#476 chore: Rename metadata -> tags in OnStatusChangeInput
  sdk-go/inferable.go
Labels: Review effort [1-5]: 1

#474 feat: Minor Playground UI fixes
  app/app/clusters/[clusterId]/agents/layout.tsx
  app/app/clusters/[clusterId]/agents/page.tsx
  app/app/clusters/[clusterId]/integrations/page.tsx
  app/app/clusters/[clusterId]/page.tsx
  app/app/clusters/[clusterId]/runs/page.tsx
  app/app/clusters/[clusterId]/settings/layout.tsx
  app/app/clusters/[clusterId]/usage/page.tsx
  app/components/WorkflowList.tsx
  app/components/chat/ToolContextButton.tsx
  app/components/cluster-runs-layout.tsx
  app/components/create-cluster-button.tsx
Labels: Review effort [1-5]: 2

#485 fix: Fix agent tests after workflow rename
  control-plane/package.json
  control-plane/src/modules/data.ts
  control-plane/src/modules/runs/agent/agent.ai.test.ts
  control-plane/src/modules/runs/agent/agent.ts
  control-plane/src/modules/runs/agent/nodes/model-call.test.ts
  control-plane/src/modules/runs/agent/run.test.ts
  control-plane/src/modules/runs/agent/summarizer.ts
  control-plane/src/modules/runs/agent/tools/cluster-internal-tools.ts
  control-plane/src/modules/runs/queues.ts
  control-plane/src/modules/runs/router.ts
  control-plane/src/modules/timeline.ts
Labels: Review effort [1-5]: 2

#486 fix: Adjust timeline fetch logic to handle empty responses and errors
  app/components/workflow.tsx
Labels: Review effort [1-5]: 2

#483 feat: Remove unused function metadata
  app/client/contract.ts
  app/components/chat/human-message.tsx
  control-plane/drizzle/0205_amusing_strong_guy.sql
  control-plane/drizzle/meta/0205_snapshot.json
  control-plane/drizzle/meta/_journal.json
  control-plane/src/modules/contract.ts
  control-plane/src/modules/data.ts
  control-plane/src/modules/router.ts
  control-plane/src/modules/runs/agent/run.ts
  control-plane/src/modules/tool-metadata.ts
Labels: Review effort [1-5]: 2

#489 chore: Call -> Job rename
  app/client/contract.ts
  app/components/chat/function-call.tsx
  app/components/workflow.tsx
  control-plane/src/bootstrap.ts
  control-plane/src/modules/contract.ts
  control-plane/src/modules/integrations/slack/index.ts
  control-plane/src/modules/integrations/toolhouse.ts
  control-plane/src/modules/jobs/create-job.ts
  control-plane/src/modules/jobs/external.ts
  control-plane/src/modules/jobs/jobs.test.ts
  control-plane/src/modules/jobs/jobs.ts
  control-plane/src/modules/jobs/router.ts
  control-plane/src/modules/jobs/self-heal-jobs.ts
  control-plane/src/modules/router.ts
  control-plane/src/modules/runs/notify.ts
Labels: Review effort [1-5]: 3

#490 chore: Reformat imports and improve code readability in prompt-textarea.tsx
  app/components/chat/prompt-textarea.tsx
Labels: Review effort [1-5]: 4

#487 feat: Support for triggering Agent from playground
  app/components/chat/prompt-textarea.tsx
  app/components/workflow.tsx
Labels: Review effort [1-5]: 3

#491 feat: Replace calls -> jobs in node SDK
  sdk-node/package.json
  sdk-node/src/Inferable.test.ts
  sdk-node/src/contract.ts
  sdk-node/src/service.ts
  sdk-node/src/tests/errors/errors.test.ts
  sdk-node/src/tests/utility/caching.test.ts
  sdk-node/src/tests/utility/retry.test.ts
Labels: Review effort [1-5]: 2

#493 feat: Replace calls -> jobs in .NET SDK
  sdk-dotnet/src/API/APIClient.cs
  sdk-dotnet/src/Service.cs
  sdk-dotnet/tests/Inferable.Tests/InferableTest.cs
Labels: Review effort [1-5]: 2

#492 feat: Replace calls -> jobs in Go SDK
  sdk-go/service.go
  sdk-go/service_test.go
Labels: Review effort [1-5]: 2

#495 feat: Render message channel in chat
  app/components/chat/human-message.tsx
  control-plane/scripts/sendTestEmail.ts
  control-plane/src/modules/email/index.ts
  control-plane/src/modules/integrations/slack/index.ts
Labels: Review effort [1-5]: 2

#494 feat: Track external messages in seperate table
  control-plane/drizzle/0206_salty_lightspeed.sql
  control-plane/drizzle/meta/0206_snapshot.json
  control-plane/drizzle/meta/_journal.json
  control-plane/src/modules/data.ts
  control-plane/src/modules/email/index.ts
  control-plane/src/modules/integrations/slack/index.ts
  control-plane/src/modules/runs/external-messages.ts
  control-plane/src/modules/runs/messages.ts
  control-plane/src/modules/runs/notify.ts
Labels: Review effort [1-5]: 3

#504 feat: New service command in the console
  app/components/cluster-details.tsx
  app/components/control-plane-box.tsx
  app/components/foo.ts
  control-plane/src/modules/auth/cluster.ts
Labels: Review effort [1-5]: 4

#507 feat: Allow Email agent association
  app/app/clusters/[clusterId]/integrations/email/page.tsx
  app/app/clusters/[clusterId]/integrations/page.tsx
  app/client/contract.ts
  control-plane/drizzle/0207_overjoyed_ronan.sql
  control-plane/drizzle/meta/0207_snapshot.json
  control-plane/drizzle/meta/_journal.json
  control-plane/scripts/sendTestEmail.ts
  control-plane/src/modules/contract.ts
  control-plane/src/modules/data.ts
  control-plane/src/modules/email/index.test.ts
  control-plane/src/modules/email/index.ts
  control-plane/src/modules/integrations/integrations.ts
  control-plane/src/modules/integrations/langfuse.ts
  control-plane/src/modules/integrations/router.ts
  control-plane/src/modules/integrations/schema.ts
  control-plane/src/modules/integrations/slack/index.ts
  control-plane/src/modules/integrations/tavily.ts
  control-plane/src/modules/integrations/types.ts
  control-plane/src/modules/integrations/valtown.ts
Labels: Review effort [1-5]: 4

#508 feat: Implement in-reply-to and references headers
  control-plane/src/modules/email/index.ts
Labels: Review effort [1-5]: 2

#505 feat: Onboarding experience and stdlib
  app/app/clusters/[clusterId]/page.tsx
  app/app/clusters/page.tsx
  app/app/setup-demo/page.tsx
  app/client/contract.ts
  app/components/chat/human-message.tsx
  app/components/chat/prompt-textarea.tsx
  app/components/chat/tool-input.tsx
  app/components/cluster-details.tsx
  app/components/clusters-table.tsx
  app/components/control-plane-box.tsx
  app/components/instructions-editor.tsx
  app/components/useClusterState.ts
  app/components/workflow.tsx
  app/tailwind.config.ts
  control-plane/drizzle/0208_brave_tenebrous.sql
  control-plane/drizzle/meta/0208_snapshot.json
  control-plane/drizzle/meta/_journal.json
  control-plane/package-lock.json
  control-plane/package.json
  control-plane/src/bootstrap.ts
  control-plane/src/modules/contract.ts
  control-plane/src/modules/data.ts
  control-plane/src/modules/management.ts
  control-plane/src/modules/router.ts
  control-plane/src/modules/runs/agent/agent.ts
  control-plane/src/modules/runs/agent/nodes/model-output.ts
  control-plane/src/modules/runs/agent/nodes/system-prompt.ts
  control-plane/src/modules/runs/agent/nodes/tool-call.ts
  control-plane/src/modules/runs/agent/run.ts
  control-plane/src/modules/runs/agent/tool.ts
  control-plane/src/modules/runs/agent/tools/calculator.ts
  control-plane/src/modules/runs/agent/tools/cluster-internal-tools.ts
  control-plane/src/modules/runs/agent/tools/date-time.ts
  control-plane/src/modules/runs/agent/tools/get-url.ts
  control-plane/src/modules/runs/agent/tools/stdlib.ts
  control-plane/src/modules/runs/messages.ts
  control-plane/src/modules/service-definitions.ts
  control-plane/src/modules/timeline.ts
  control-plane/src/utilities/env.ts
Labels: Review effort [1-5]: 4

#510 fix: Correct import formatting and improve code readability in Slack integration
  app/app/clusters/[clusterId]/integrations/slack/page.tsx
Labels: Review effort [1-5]: 2

#511 fix: Update default max database connections to 20
  control-plane/src/utilities/env.ts
Labels: Review effort [1-5]: 1

#513 chore: Add tests around Slack cleanup logic
  control-plane/src/modules/integrations/slack/index.test.ts
  control-plane/src/modules/integrations/slack/index.ts
Labels: Review effort [1-5]: 2

#514 fix: Re-add agent tab in Runs page
  app/components/chat/prompt-textarea.tsx
Labels: Review effort [1-5]: 2

#515 fix: Refactor error handling in API key creation
  app/components/cluster-details.tsx
Labels: Review effort [1-5]: 2

#516 chore: Relocate TypeScript demos to monorepo
  demos/typescript/.gitignore
  demos/typescript/LICENSE
  demos/typescript/README.md
  demos/typescript/database.sqlite
  demos/typescript/index.ts
  demos/typescript/package-lock.json
  demos/typescript/package.json
  demos/typescript/secret.ts
  demos/typescript/sql-to-text/seed.ts
  demos/typescript/sql-to-text/service.ts
  demos/typescript/terminal-copilot/service.ts
  demos/typescript/tsconfig.json
Labels: Review effort [1-5]: 4

#517 fix: Remove redundant toast notifications and streamline demo cluster setup
  app/app/setup-demo/page.tsx
  app/client/contract.ts
  app/components/breadcrumbs.tsx
  app/components/chat/prompt-textarea.tsx
  app/components/useClusterState.ts
  control-plane/src/modules/contract.ts
  control-plane/src/modules/management.ts
  demos/typescript/sql-to-text/service.ts
Labels: Review effort [1-5]: 3

#518 fix: Adjust service timeout to 1 minute and add descriptions to functions
  app/components/cluster-details.tsx
  app/components/useClusterState.ts
  app/components/workflow.tsx
  app/lib/use-hash-state.ts
  app/lib/use-json-state.ts
  control-plane/src/modules/service-definitions.ts
  demos/typescript/sql-to-text/service.ts
  demos/typescript/terminal-copilot/service.ts
Labels: Review effort [1-5]: 3

#519 feat: Make Toolhouse permanent
  control-plane/src/modules/integrations/toolhouse.ts
Labels: Review effort [1-5]: 2

#523 feat: Add hyperDX for FE telemetry
  app/app/layout.tsx
  app/instrumentation.ts
  app/lib/hyperdx.ts
  app/next.config.mjs
  app/package-lock.json
  app/package.json
Labels: Review effort [1-5]: 2

#524 chore: Disable hyperdx advanced capture
  app/lib/hyperdx.ts
Labels: Review effort [1-5]: 1

#525 chore: Dissable hyperDX replays in FE
  app/lib/hyperdx.ts
Labels: Review effort [1-5]: 1

#526 fix: Remove service poll throttle
  control-plane/src/modules/service-definitions.ts
Labels: Review effort [1-5]: 1

#528 fix: Refactor CSS class handling for message component
  app/components/chat/human-message.tsx
Labels: Review effort [1-5]: 1

#530 fix: Remove knowledge artifact related code and components
  app/app/clusters/[clusterId]/knowledge/[artifactId]/edit/page.tsx
  app/app/clusters/[clusterId]/knowledge/layout.tsx
  app/app/clusters/[clusterId]/knowledge/new/page.tsx
  app/app/clusters/[clusterId]/knowledge/page.tsx
  app/app/clusters/[clusterId]/settings/details/page.tsx
  app/client/contract.ts
  app/components/KnowledgeArtifactForm.tsx
  cli/src/client/contract.ts
  control-plane/src/modules/contract.ts
  control-plane/src/modules/knowledge/knowledgebase.test.ts
  control-plane/src/modules/knowledge/knowledgebase.ts
  control-plane/src/modules/observability/events.ts
  control-plane/src/modules/router.ts
  control-plane/src/modules/runs/agent/agent.ts
  control-plane/src/modules/runs/agent/nodes/model-output.ts
  control-plane/src/modules/runs/agent/nodes/system-prompt.ts
  control-plane/src/modules/runs/agent/nodes/tool-call.ts
  control-plane/src/modules/runs/agent/run.ts
  control-plane/src/modules/runs/agent/tool.ts
  control-plane/src/modules/runs/agent/tools/calculator.ts
  control-plane/src/modules/runs/agent/tools/cluster-internal-tools.ts
  control-plane/src/modules/runs/agent/tools/date-time.ts
  control-plane/src/modules/runs/agent/tools/get-url.ts
  control-plane/src/modules/runs/agent/tools/knowledge-artifacts.ts
  control-plane/src/modules/runs/agent/tools/stdlib.ts
Labels: Review effort [1-5]: 4

#533 feat: Add demo source links for sqlite and terminal services
  app/components/chat/prompt-textarea.tsx
  app/components/cluster-details.tsx
Labels: Review effort [1-5]: 2

#531 fix: Refactor run handling to use run object instead of runId
  control-plane/src/modules/auth/auth.test.ts
  control-plane/src/modules/data.ts
  control-plane/src/modules/router.ts
  control-plane/src/modules/runs/agent/agent.ai.test.ts
  control-plane/src/modules/runs/agent/agent.ts
  control-plane/src/modules/runs/agent/nodes/edges.test.ts
  control-plane/src/modules/runs/agent/nodes/model-call.test.ts
  control-plane/src/modules/runs/agent/nodes/model-output.test.ts
  control-plane/src/modules/runs/agent/nodes/tool-call.test.ts
  control-plane/src/modules/runs/agent/nodes/tool-call.ts
  control-plane/src/modules/runs/agent/run.test.ts
  control-plane/src/modules/runs/agent/run.ts
  control-plane/src/modules/runs/agent/state.ts
  control-plane/src/modules/runs/index.test.ts
  control-plane/src/modules/runs/index.ts
  control-plane/src/modules/runs/notify.ts
  control-plane/src/modules/runs/queues.ts
  control-plane/src/modules/runs/router.ts
  control-plane/src/modules/runs/summarization.ts
Labels: Review effort [1-5]: 3

#540 fix: Add event logging for job approval actions
  control-plane/src/modules/jobs/jobs.ts
  control-plane/src/modules/observability/events.ts
Labels: Review effort [1-5]: 2

#541 fix: Hide buttons in chat and workflow components
  app/components/chat/human-message.tsx
  app/components/workflow.tsx
Labels: Review effort [1-5]: 1

#542 fix: Remove unused getServerStats endpoint and method
  control-plane/src/modules/contract.ts
  control-plane/src/modules/router.ts
Labels: Review effort [1-5]: 1

#547 fix: Remove crisp
  .github/workflows/build.yml
  app/Dockerfile
  app/app/layout.tsx
  app/components/crisp-chat.tsx
  app/package-lock.json
  app/package.json
Labels: Review effort [1-5]: 1

#548 fix: Add dialog for manual command copy on clipboard error
  app/components/cluster-details.tsx
Labels: Review effort [1-5]: 2

#553 fix: Refactor cluster state management and remove unused imports
  app/client/contract.ts
  app/components/cluster-details.tsx
  app/components/instructions-editor.tsx
  app/components/useClusterState.ts
  control-plane/src/modules/auth/custom.ts
  control-plane/src/modules/contract.ts
  control-plane/src/modules/data.ts
  control-plane/src/modules/management.ts
Labels: Review effort [1-5]: 3

#556 chore: Revise README for clarity and add new sections
  README.md
Labels: Review effort [1-5]: 1

#558 fix: Correct error handling in authentication process
  app/components/header.tsx
Labels: Review effort [1-5]: 1

#559 fix: Integrate Slack help icon into navigation bar
  app/app/layout.tsx
  app/components/error-display.tsx
Labels: Review effort [1-5]: 2

#560 fix: Usability changes to runs
  app/components/breadcrumbs.tsx
  app/components/chat/ToolContextButton.tsx
  app/components/chat/function-call.tsx
  app/components/chat/prompt-textarea.tsx
  app/components/clusters-table.tsx
Labels: Review effort [1-5]: 3

#561 fix: Ensure unique machines and services in cluster details
  control-plane/src/modules/management.ts
Labels: Review effort [1-5]: 2

#564 fix: Streamline run timeline fetching and rendering
  app/app/clusters/[clusterId]/runs/[runId]/page.tsx
  app/app/clusters/[clusterId]/settings/details/page.tsx
  app/client/client.ts
  app/client/contract.ts
  app/components/breadcrumbs.tsx
  app/components/chat/function-call.tsx
  app/components/workflow.tsx
Labels: Review effort [1-5]: 4

#578 fix: update CLI options in README and code for consistency
  adapters/pgsql-adapter/README.md
  adapters/pgsql-adapter/src/index.ts
Labels: Review effort [1-5]: 1

#580 chore: update README and UI components for consistency
  adapters/pgsql-adapter/README.md
  adapters/valtown-adapter/README.md
  app/app/clusters/[clusterId]/integrations/page.tsx
  app/components/cluster-details.tsx
Labels: Review effort [1-5]: 2

#581 refactor: streamline email integration imports and update integration config
  app/app/clusters/[clusterId]/integrations/email/page.tsx
  app/app/clusters/[clusterId]/integrations/page.tsx
  app/app/clusters/[clusterId]/integrations/zapier/page.tsx
  app/app/clusters/layout.tsx
Labels: Review effort [1-5]: 3

#584 fix: improve URL validation and token handling in Valtown integration
  app/app/clusters/[clusterId]/integrations/valtown/page.tsx
  control-plane/src/modules/integrations/integrations.ts
Labels: Review effort [1-5]: 3

#589 feat: Expose standard library prominently in the console
  app/app/clusters/[clusterId]/agents/new/page.tsx
  app/app/globals.css
  app/components/breadcrumbs.tsx
  app/components/chat/agent-form.tsx
  app/components/chat/prompt-textarea.tsx
  app/components/chat/structured-output-editor.tsx
  app/components/cluster-details.tsx
  app/components/error-display.tsx
  app/components/ui/send-button.tsx
  control-plane/.env.base
  control-plane/docker-compose.yml
  control-plane/src/modules/runs/agent/run.ts
  control-plane/src/modules/runs/agent/tools/get-url.ts
Labels: Review effort [1-5]: 4

#591 chore: Revamp README.md with updated features and demo links
  README.md
  assets/demo.png
  assets/hero.png
Labels: Review effort [1-5]: 1

#593 fix: replace demo video link with thumbnail image in README.md
  README.md
  assets/thumbnail.png
Labels: Review effort [1-5]: 1

#603 chore: Remove unused demo image from README.md
  README.md
Labels: Review effort [1-5]: 1

#626 fix: Control plane local dev setup
  control-plane/.env.base
  control-plane/docker-compose.dev.yml
  control-plane/docker-compose.yml
Labels: Review effort [1-5]: 1

#627 chore: Inline decoupled routes into main router file
  control-plane/src/modules/auth/router.ts
  control-plane/src/modules/integrations/constants.ts
  control-plane/src/modules/integrations/router.ts
  control-plane/src/modules/jobs/router.ts
  control-plane/src/modules/machines/constants.ts
  control-plane/src/modules/machines/router.ts
  control-plane/src/modules/router.ts
  control-plane/src/modules/runs/router.ts
Labels: Review effort [1-5]: 4
